documents = [
    {
        "preq": "[]",
        "creq": "[]",
        "depn": "[]",
        "_id": "62bed48b71b2809473f23a29",
        "dept": "ACAM",
        "code": "ACAM 350",
        "cred": "3",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=ACAM&course=350",
        "name": "Asian Canadian Community-Based Media",
        "desc": "Digital media production in the context of community engagement. Includes critical media literacy, community-based research ethics, project design, training in media forms such audio, video, photography, and web publishing.",
        "average": "85.13"},
    {
        "preq": "[]",
        "creq": "[]",
        "depn": "[]",
        "_id": "62bed48b71b2809473f23a2e",
        "dept": "ADHE",
        "code": "ADHE 327",
        "cred": "3",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=ADHE&course=327",
        "name": "Teaching Adults",
        "desc": "Planning, conducting and evaluating instruction for adults. Consideration is given to different beliefs and ways of thinking about teaching. [3-0-0]"},
    {
        "preq": "[]",
        "creq": "[]",
        "depn": "[]",
        "_id": "62bed48b71b2809473f23a6d",
        "dept": "AMNE",
        "code": "AMNE 364",
        "cred": "3",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=AMNE&course=364",
        "name": "Prophecy in the Bible and the Ancient Near East",
        "desc": "An exploration of the unique phenomenon of the biblical prophet in its wider Near Eastern context. Credit will be granted for only one of RELG 305 or AMNE 364."},
    {
        "preq": "[]",
        "creq": "[]",
        "depn": "[]",
        "_id": "62bed48b71b2809473f23a6e",
        "dept": "AMNE",
        "code": "AMNE 366",
        "cred": "3",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=AMNE&course=366",
        "name": "The Origins of Christianity: Social, Religious, and Political Milieux",
        "desc": "The origins of Christianity as reflected in early Christian literature of the first and early second centuries (including the New Testament). Credit will be granted for only one of RELG 317 or AMNE 366."},
    {
        "preq": "[]",
        "creq": "[]",
        "depn": "[]",
        "_id": "62bed48b71b2809473f23a82",
        "dept": "AMNE",
        "code": "AMNE 462",
        "cred": "None",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=AMNE&course=462",
        "name": "Seminar in Early Judaism",
        "desc": "Selected topics in Judaism and Hellenism, the rise of the synagogue, Jewish sects, the development of classical rabbinic literature (e.g., Mishnah, Talmud, Midrash). A maximum of 6 credits will be granted for AMNE 462 or RELG 407. Students should consult the AMNE Undergraduate Advisor before registering."},
    {
        "preq": "[]",
        "creq": "[]",
        "depn": "[]",
        "_id": "62bed48b71b2809473f23a85",
        "dept": "AMNE",
        "code": "AMNE 470",
        "cred": "None",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=AMNE&course=470",
        "name": "Seminar in Ancient Mediterranean and Near Eastern Archaeology",
        "desc": "Selected topics in the art, archaeology and/or architecture of the ancient Mediterranean, Near East and/or Egypt, with an emphasis on research. A maximum of 12 credits will be granted for AMNE 470 and CLST 403. Students should consult the AMNE Undergraduate Advisor before registering. This course is not eligible for Credit/D/Fail grading."},
    {
        "preq": "[]",
        "creq": "[]",
        "depn": "[]",
        "_id": "62bed48b71b2809473f23a87",
        "dept": "AMNE",
        "code": "AMNE 472",
        "cred": "3",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=AMNE&course=472",
        "name": "The Archaeology of Ancient Cyprus",
        "desc": "An overview of the archaeology of ancient Cyprus from the island's initial colonization in the 10th millennium BCE through the period of its rule as part of the Roman Empire (4th century CE). Credit will be granted for only one of CNRS 410 or AMNE 472."},
    {
        "preq": "['ANTH 100']",
        "creq": "[]",
        "depn": "['ANTH 300']",
        "_id": "62bed48b71b2809473f23a91",
        "dept": "ANTH",
        "code": "ANTH 200",
        "cred": "3",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=ANTH&course=200",
        "name": "Introduction to Problems in Method and Theory in Anthropology",
        "desc": "A survey of basic concepts and procedures in the cross-cultural study of human societies.",
        "prer": "ANTH 100."},
    {
        "title": "What's the best hackathon in the world",
        "text": "Hack the North of course"}
]

documents2 = [
    {
        "preq": "[]",
        "creq": "[]",
        "depn": "[]",
        "_id": "62bed48b71b2809473f23a29",
        "dept": "ACAM",
        "code": "ACAM 350",
        "cred": "3",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=ACAM&course=350",
        "name": "Asian Canadian Community-Based Media",
        "desc": "Digital media production in the context of community engagement. Includes critical media literacy, community-based research ethics, project design, training in media forms such audio, video, photography, and web publishing.",
        "average": "85.13"
    },
    {
        "preq": "[]",
        "creq": "[]",
        "depn": "[]",
        "_id": "62bed48b71b2809473f23a2e",
        "dept": "ADHE",
        "code": "ADHE 327",
        "cred": "3",
        "link": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=ADHE&course=327",
        "name": "Teaching Adults",
        "desc": "Planning, conducting and evaluating instruction for adults. Consideration is given to different beliefs and ways of thinking about teaching. [3-0-0]"
    }
]